try{
    const k = 5;
     //k = 20;
    console.log(k);
}
catch(error)
{
    console.log(error);
}
finally {
    console.log("Execution Completed...")
}